### ISSUE TITLE
WebpackError: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by rique-dev** [quan-to/connect-web-embedded#11]
Hello, Henrique of @noverde.

We are using the lib to connect in a gatsby application, but we are receiving this error when building it.

```
gatsby build
``` 

![image](https://user-images.githubusercontent.com/11713190/92636571-f7dde580-f2ad-11ea-8426-7f1032b5d4aa.png)

**Comment by nic** [comment]
Thanks a lot! ❤️
